"""empty message

Revision ID: aa02e2d4e6ca
Revises: 
Create Date: 2020-02-08 12:32:11.632868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa02e2d4e6ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('teams_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_name', sa.String(length=255), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_name', sa.String(length=255), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('date_results_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_results_id'], ['date_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_results_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams_scores')
    op.drop_table('date_results')
    # ### end Alembic commands ###
