"""empty message

Revision ID: e4e5b487a26b
Revises: aa02e2d4e6ca
Create Date: 2020-02-08 14:25:01.403859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e5b487a26b'
down_revision = 'aa02e2d4e6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'date_results', ['id'])
    op.drop_constraint('teams_scores_date_results_id_key', 'teams_scores', type_='unique')
    op.create_unique_constraint(None, 'teams_scores', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams_scores', type_='unique')
    op.create_unique_constraint('teams_scores_date_results_id_key', 'teams_scores', ['date_results_id'])
    op.drop_constraint(None, 'date_results', type_='unique')
    # ### end Alembic commands ###
